USE colecao_album_copa;

CREATE TABLE IF NOT EXISTS usuario(
  CPF CHAR(11) NOT NULL,
  Senha CHAR(8) NOT NULL,
  Nome VARCHAR(60) NOT NULL,
  Inter_Classe BOOL NOT NULL DEFAULT False,
  Qtt TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(CPF)
);

CREATE TABLE IF NOT EXISTS figurinha(
  ID SMALLINT(3) UNSIGNED NOT NULL,
  Nome VARCHAR(100) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS jogador(
  ID SMALLINT(3) UNSIGNED NOT NULL,
  Clube VARCHAR(30) NOT NULL,
  Peso FLOAT(3,1) NOT NULL,
  Altura FLOAT(3,2) NOT NULL,
  Nascimento DATE NOT NULL,
  Convocacao YEAR NOT NULL,
  Posicao CHAR(3) NOT NULL,
  Pais VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS especial(
  ID SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS escudo(
  ID SMALLINT(3) UNSIGNED NOT NULL,
  Pais VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS selecao(
  ID SMALLINT(3) UNSIGNED NOT NULL,  
  Pais VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS estadio(
  ID SMALLINT(3) UNSIGNED NOT NULL,
  Cidade VARCHAR(20) NOT NULL,
  Capacidade MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS poster(
  ID SMALLINT(3) UNSIGNED NOT NULL,
  Cidade VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS fig_colecao(
  Usuario CHAR(11) NOT NULL,
  ID SMALLINT(3) UNSIGNED NOT NULL,
  Quantidade TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (Usuario, ID),
  FOREIGN KEY (Usuario) REFERENCES usuario (CPF) ON DELETE CASCADE,
  FOREIGN KEY (ID) REFERENCES figurinha (ID) 
);

CREATE TABLE IF NOT EXISTS troca(
  ID BIGINT UNSIGNED NOT NULL,
  De CHAR(11) NOT NULL,
  Para CHAR(11) NOT NULL,
  Fig SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (De) REFERENCES usuario (CPF) ON DELETE CASCADE,
  FOREIGN KEY (Para) REFERENCES usuario (CPF) ON DELETE CASCADE,
  FOREIGN KEY (Fig) REFERENCES figurinha (ID)
);

CREATE TABLE IF NOT EXISTS recomendadas(
  ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES troca (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ativas(
  ID BIGINT UNSIGNED NOT NULL,
  Completada BOOL NOT NULL DEFAULT False,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES troca (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS relacionamento_trocas_ativas(
  Troca1 BIGINT UNSIGNED NOT NULL,
  Troca2 BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (Troca1, Troca2),
  FOREIGN KEY (Troca1) REFERENCES ativas (ID) ON DELETE CASCADE,
  FOREIGN KEY (Troca2) REFERENCES ativas (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS relacionamento_troca_recomendadas(
  Troca1 BIGINT UNSIGNED NOT NULL,
  Troca2 BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (Troca1, Troca2),
  FOREIGN KEY (Troca1) REFERENCES recomendadas (ID) ON DELETE CASCADE,
  FOREIGN KEY (Troca2) REFERENCES recomendadas (ID) ON DELETE CASCADE
);

